### ISSUE TITLE
Error FATAL: couldn't open logfile /var/fof-data//fof-install.log

### ISSUE THREAD

**Issue by debby1** [RomanSixty/Feed-on-Feeds#22]
Hi, I can't install this on my server :(

Warning: fopen(/var/fof-data//fof-install.log): failed to open stream: No such file or directory in /srv/users/mypathsite/public/fof/fof-main.php on line 85
FATAL: couldn't open logfile /var/fof-data//fof-install.log

In fof-config.php I have added Database connection information (localhost, database name user password), chose a backend: define('USE_MYSQL', 1); and tried with define('SQL_NO_TRIGGERS', 1); commented and uncommented..doesn't work, always errors :(

I try to install it also on locale with xampp but nothing, same error code.

How can I install it? Thank you in advance

**Comment by RomanSixty** [comment]
Closing because issue is pretty old and diverged from the original (and answered) question.
