### ISSUE TITLE
Is this the best feed-of-feeds to use a s a base for more development?

### ISSUE THREAD

**Issue by pperrin** [RomanSixty/Feed-on-Feeds#25]
I've been using the original (version .5) for some time, I need to do some work on it and found this repo - is this the latest/greatest version?

**Comment by plaidfluff** [comment]
I recommend looking at my branch, as I've added a bunch of stuff that RomanSixty hasn't merged back in yet (such as demand-loading images and a bunch of little fixups).

**Comment by pperrin** [comment]
Cheers - am half way through upgrading (as you may see from the issues!) once thats done I'll take a look. Just need my server PHP upgraded as 5.3.1 is the latest installed :( - hopefully by tomorrow!

**Comment by plaidfluff** [comment]
Yeah, feel free to submit a patch for the version check. :) I should make sure I have issues enabled on my fork since I don't think RomanSixty even checks this anymore and we've kind of diverged.

**Comment by fluffy-critter** [comment]
And I take back what I said above - and want to express my extreme appreciation for all the work @RomanSixty has done over the years and continues to do.
