### ISSUE TITLE
Needs PHP 5.3.6 or higher as it uses 'saveHTML' with a parameter in plugin/item_targets.php

### ISSUE THREAD

**Issue by pperrin** [RomanSixty/Feed-on-Feeds#27]
Install needs to checck for PHP 5.3.6 or higher (or the plugin does? if they are meant to be separately installable?).

First Screen shows...

[« previous 50] [all-at-once]

Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /usr/local/home/httpd/vhtdocs/idltd/apps/fof/plugins/item_targets.php on line 36

Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /usr/local/home/httpd/vhtdocs/idltd/apps/fof/plugins/item_targets.php on line 36

Warning: DOMDocument::saveHTML() expects exactly 0 parameters, 1 given in /usr/local/home/httpd/vhtdocs/idltd/apps/fof/plugins/item_targets.php on line 36

**Comment by plaidfluff** [comment]
You can disable individual plugins on your preferences page. That's a good thing to check anyway though.

Also I suppose I should turn my demand-loaded images thing into a plugin instead of hardcoding it into `fof_render`.

**Comment by pperrin** [comment]
I haven't got into the 'plugin' architecture thing yet(!). But I'll have- a look at turning it off while the server is getting its upgrade thanks!

**Comment by RomanSixty** [comment]
`item_targets.php` nowadays looks nothing like a few years back, so I guess this issue can be closed.

Also as much as I'm a fan of supporting older environments... according to [php.net](http://php.net/supported-versions.php) version 5.3 reached end of life even when this issue was opened.
