### ISSUE TITLE
'j' paging-down gets stuck on longer entries now

### ISSUE THREAD

**Issue by fluffy-critter** [RomanSixty/Feed-on-Feeds#34]
I don't know how much of this is due to the recent-ish migration away from prototype or some of the styling changes or whatever, but now when I press `j` on some feed items, the paging stops working partway through.

One example entry that causes the problem is https://99percentinvisible.org/episode/raccoon-resistance/ which is on a blog which often has quite long posts. It seems that all of their posts cause this problem. On some of them my browser's developer console gets errors like:

> TypeError: null is not an object (evaluating 'itemElement.nextElementSibling.id') on fof.js:261

I haven't looked at the new code  yet but I suspect there's been some DOM change which causes this quirk.

It happens in Safari, and I haven't tried it in other browsers yet.

`J` paging (to mark and skip to the next entry) continues to work, at least.

**Comment by fluffy-critter** [comment]
Hm, it seems that paging past the last entry also no longer triggers the "Mark all flagged items read?" popup.

**Comment by RomanSixty** [comment]
I stumbled upon the keyboard navigation feature when I made my changes to get rid of prototype. I tried to keep all the functionality but it was more or less a blind run since I'm not using the feature. So I may have missed some hopefully minor feature (like the one mentioned in your latest comment). I may look into it when I have some time to spare, except if you fix it first ;)

**Comment by RomanSixty** [comment]
However I may have found why keyboard navigation using `j` broke with large items. Take a look into 3a15d393efd3aa47f1a09381f8ebfea1cb1b3aa1

**Comment by fluffy-critter** [comment]
Hmm, it still doesn't work quite right: lowercase `j` is now paging down a whole entry at a time (which is what capital `J` does normally) and it's not showing the "mark all flagged read?" prompt after paging past the last one. That change alone shouldn't be causing *that* sort of difference so maybe I just need to go through and rework the keyboard paging code myself...

**Comment by RomanSixty** [comment]
I found the "mark all flagged read" stuff, I migrated it when refactoring. However the bug with large items was also migrated from the old code, so it probably was already broken... :)

However I did some more refactoring and now I'm getting the prompt after the last item. See c7055e241398438f8db6edea88cee87a72f79770

**Comment by fluffy-critter** [comment]
It was definitely not broken from the previous time I merged from you. :) Looks like that was way back in May, at 0da2b162d6d2ed415778562b125083a2461f46a2.

Anyway I'll try this new change out!

**Comment by fluffy-critter** [comment]
Anyway the major problem has been fixed so I'll close this issue, and I'll hack on the actual paging behavior to get it nice again on my own. :)

As always, thanks!
