### ISSUE TITLE
File authorship information needs updating

### ISSUE THREAD

**Issue by fluffy-critter** [RomanSixty/Feed-on-Feeds#35]
Most of the files in the source only refer to Steve Minutillo's contributions and copyright, but there are a bunch of other people who have worked on it since then. And how much of the original code even remains at this point?

We should probably go through and update the copyright of the source files to include all the contributors thereof to properly credit everyone. How does this even work with the GPL, anyway?

**Comment by RomanSixty** [comment]
Good Point. ae8a14f1376103beda32bcb655958ea1e2b74ccc added a list of contributors to the README file. Actually I wanted to remove the copyright notice and license disclaimer at the top of each source code file. But these notices are actually recommended by [gnu.org](https://www.gnu.org/licenses/gpl-howto.html) so I left them in place.

**Comment by RomanSixty** [comment]
I guess the current solution is a good compromise.
