### ISSUE TITLE
Can you support docker?

### ISSUE THREAD

**Issue by wjx0912** [RomanSixty/Feed-on-Feeds#38]
it's convenient installation, thanks.

**Comment by wjx0912** [comment]
hi, @fluffy-critter 
thanks for your reply, a example: https://github.com/typecho/typecho/blob/master/tools/Dockerfile
such a command like this will be convenient:
docker run -v /my_backup_path:/root/feed-on-feeds -p 8080:80 RomanSixty/Feed-on-Feeds

thank you~

**Comment by RomanSixty** [comment]
Since it's hard to support something I personally don't use I'd welcome pull requests from users who know what they are doing :)
